name: Scott Linder
title: Scott Linder
email: scott@scottlinder.com
description: "Homepage of Scott Linder"
baseurl: ""
url: "http://www.scottlinder.com/"
navs:
  - name: About
    url: /about/
  - name: Talks
    url: /talks/
  - name: Blog
    url: /blog/
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM
  hard_wrap: false
permalinks: pretty
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
